name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  build:
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
        jdk: [ 'temurin' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} ${{ matrix.jdk }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.jdk }}
          cache: 'gradle'
      - name: Gradle build
        run: ./gradlew build
